using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using static UnityEditor.Searcher.SearcherWindow.Alignment;

public class PlayerController : MonoBehaviour
{
   
    public InputAction MoveAction;


    public float Horizontal { get; private set; }

    // Start is called before the first frame update
    void Start()
    {
        MoveAction.Enable();
        


    }
    // update is called once per frame
    void Update()
    {
        Vector2 move = MoveAction.ReadValue<Vector2>();
        Debug.Log(move);
        Vector2 position = (Vector2)transform.position + move * 0.01f;
        transform.position = position;
    }
}

